### ISSUE TITLE
Bower script injection

### ISSUE THREAD

**Issue by resadzacina** [eight04/angular-ezdialog#1]
The script and css files are not injected automatically using Bower.

**Comment by eight04** [comment]
I thought Bower is a dependency manager. What does "inject automatically" mean?

**Comment by resadzacina** [comment]
When trying to install angular-ezdialog from the bower directory using `bower install angular-ezdialog` the  package is downloaded to the bower_components folder which is fine, but for full integration with Bower the scripts that are defined in the `main` block of your bower.json could/should be injected in the hosting app automatically. In my case it is an Angular SPA app that is using Grunt and a good way to inject the dependencies in the html file it is to run a `grunt wiredep` which will do the magic. Maybe a readme file update for Grunt users would work.

**Comment by eight04** [comment]
I've installed and set up grunt-wiredep. I tried
1.  Add `<!-- bower:css --><!-- endbower --> <!-- bower:js --><!-- endbower -->` into index.html header.
2.  `bower install angular-ezdialog --save`
3.  `grunt wiredep`

And the css and js files were successfully injected to index.html like this

```
<!-- bower:css -->
<link rel="stylesheet" href="bower_components/angular-ezdialog/dist/dialog.css" />
<!-- endbower -->
<!-- bower:js -->
<script src="bower_components/angular-ezdialog/dist/dialogs.js"></script>
<!-- endbower -->
```

I guess wiredep is using bower's main file list. Could you post the `bower.json` under `bower_components/angular-ezdialog/` ?

**Comment by resadzacina** [comment]
The problem is that the version I was initially using (1.0.4) doesn't have the `main` section defined in the `bower` file and it looks like:

{
  "name": "angular-ezdialog",
  "homepage": "https://github.com/eight04/angular-ezdialog",
  "version": "1.0.4",
  "_release": "1.0.4",
  "_resolution": {
    "type": "version",
    "tag": "v1.0.4",
    "commit": "7386fc69fb2bf52cf39e3c90cc5aaa5b9b1e35a1"
  },
  "_source": "git://github.com/eight04/angular-ezdialog.git",
  "_target": "1.0.4",
  "_originalSource": "angular-ezdialog"
}

Seems it is resolved in the latest version and it can be installed and injected with `wiredep` exactly as you highlighted above.
